spring:
  application:
    name: eureka1
server:
  port: 8761

eureka:
  instance:
    hostname:eurekaserver1
  client:
    service-url:
      defaultZone: http://eurekaserver2:8761/eureka/
  server:
    enable-self-preservation: false

management:
  endpoints:
    web:
      exposure:
        include: *